### ISSUE TITLE
Custom action: Add support for arbitrary arguments/flags

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-terraform#24]
This mixin currently has rudimentary custom action support for use in a `porter.yaml` manifest, e.g.

```
customActions:
  plan:
    description: "Invoke 'terraform plan'"
    modifies: false
    stateless: true
...
plan:
  - terraform:
      description: "Invoke 'terraform plan'"
      # by default, the mixin will call terraform with a command
      # with the same name as the custom action; however, we can
      # override with:
      command: "plan"
```

However, a custom action might require an arbitrary set of args/options to send along to terraform.  Therefore, we have a need to add an additional `args` block to support this... perhaps something like:

```
plan:
  - terraform:
      description: "Invoke 'terraform plan'"
      command: "plan"
      args:
        - "-var foo=bar"
        - "-refresh=true"
...
```

Or, similar to how the exec mixin does things, a `flags` block:
```
plan:
  - terraform:
      description: "Invoke 'terraform plan'"
      command: "plan"
      flags:
        var: foo=bar
        refresh: true
...
```
